// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type User struct {
	ID           interface{}
	Email        string
	Username     sql.NullString
	Profileindex sql.NullString
}
